services:
  - type: web
    name: utmconnect
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ''
    startCommand: ''
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:dfkbRxXa8jCzOv3YYl81XCzrl8p/S635kOem8lss+5k=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://utmconnect.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: utmconnect
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 
