services:
  - type: web
    name: utmconnect
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ''
    startCommand: ''
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: bbase64:5kmng2qGtPl58RbJzRuN7mznCyEJhgocBo8pjjK5mII=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://utmconnect.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: dpg-d13bhgh5pdvs73dif870-a
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: utmconnect
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: d5jbTeUbFL75P7nwiEJGK7MnonKZzkAd
