services:
  - type: web
    name: utmconnect
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    buildCommand: ''
    startCommand: ''
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:5kmng2qGtPl58RbJzRuN7mznCyEJhgocBo8pjjK5mII=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://utmconnect-production-8bcf.up.railway.app
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: utmconnect+
      - key: DB_USERNAME
        value: user
      - key: DB_PASSWORD
        value: userpass
